/**
 * This file is autogenerated by Scaffold-Stark.
 * You can edit it to add your own external contracts.
 */

import deployedContracts from "./deployedContracts";

const configExternalContracts = {
    sepolia: {
        // Import address and classHash from deployedContracts.ts
        "MineToken": {
            address: deployedContracts.sepolia.MineToken.address,
            classHash: deployedContracts.sepolia.MineToken.classHash,
        },
        "MinerNFT": {
            address: deployedContracts.sepolia.MinerNFT.address,
            classHash: deployedContracts.sepolia.MinerNFT.classHash,
        },
        "CoreEngine": {
            address: deployedContracts.sepolia.CoreEngine.address,
            classHash: deployedContracts.sepolia.CoreEngine.classHash,
        },
        "StationSystem": {
            address: deployedContracts.sepolia.StationSystem.address,
            classHash: deployedContracts.sepolia.StationSystem.classHash,
        },
        "MergeSystem": {
            address: deployedContracts.sepolia.MergeSystem.address,
            classHash: deployedContracts.sepolia.MergeSystem.classHash,
        },
        "RewardDistributor": {
            address: deployedContracts.sepolia.RewardDistributor.address,
            classHash: deployedContracts.sepolia.RewardDistributor.classHash,
        },
    },
    // Add other networks as needed
} as const;

export default configExternalContracts;
